#!/bin/bash  

# delete event bridge target (& aws managed target)
#aws events list-targets-by-rule --rule StepFunctionsGetEventsForBatchJobsRule
aws events remove-targets --rule Retail_ELT_Batch_Rule --ids "1"
aws events remove-targets \
    --rule StepFunctionsGetEventsForBatchJobsRule \
    --ids "StepFunctionsGetEventsForBatchJobsRule-Id" --force

# delete event bridge rule (& managed rule that gets generated by AWS)
aws events delete-rule --name Retail_ELT_Batch_Rule
aws events delete-rule --name StepFunctionsGetEventsForBatchJobsRule --force


# delete step function 
aws stepfunctions delete-state-machine \
    --state-machine-arn arn:aws:states:eu-west-2:503289723064:stateMachine:Retail_Batch_ELT 

# end 